# Generated by Django 5.0 on 2023-12-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_invoicecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, default='Unknown', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='postcode',
            field=models.CharField(blank=True, default='Unknown', max_length=10, null=True),
        ),
    ]
