# Generated by Django 5.0 on 2023-12-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('goals_active', models.IntegerField(default=0)),
                ('goals_completed', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0, help_text='Percentage of goals completed')),
                ('tasks_due', models.IntegerField(default=0)),
                ('performance_score', models.IntegerField(default=0, help_text='Performance score out of 100')),
                ('success_rate', models.IntegerField(default=0, help_text='Success rate based on projects')),
                ('innovation_score', models.IntegerField(default=0, help_text='Score for innovation and ideas')),
            ],
        ),
    ]
