# Generated by Django 5.0 on 2023-12-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='schools',
            field=models.ManyToManyField(related_name='employees', to='schools.school'),
        ),
    ]
